-- Основная таблица чатов
CREATE TABLE public.chat
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    title      VARCHAR(255)
);

ALTER TABLE public.chat
    OWNER TO postgres;

-- Таблица записей чата
CREATE TABLE public.chat_entry
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT,
    created_at TIMESTAMP(6),
    role       VARCHAR(255)
        CONSTRAINT chat_entry_role_check
            CHECK ((role)::TEXT = ANY (ARRAY ['USER'::CHARACTER VARYING, 'ASSISTANT'::CHARACTER VARYING]::TEXT[])),
    chat_id    BIGINT
        CONSTRAINT fkqcc1bnu77jh530e61twlq52ja
            REFERENCES public.chat (id)
);

ALTER TABLE public.chat_entry
    OWNER TO postgres;
